// Mocks generated by Mockito 5.0.17 from annotations
// in crypto_tracker_app/test/data/models/response/coin_response_test.dart.
// Do not manually edit this file.

import 'package:crypto_tracker_app/data/models/coin_properties_model/community_data_response.dart'
    as _i6;
import 'package:crypto_tracker_app/data/models/coin_properties_model/description_response.dart'
    as _i3;
import 'package:crypto_tracker_app/data/models/coin_properties_model/developer_data_response.dart'
    as _i7;
import 'package:crypto_tracker_app/data/models/coin_properties_model/image_response.dart'
    as _i5;
import 'package:crypto_tracker_app/data/models/coin_properties_model/links_response.dart'
    as _i4;
import 'package:crypto_tracker_app/data/models/coin_properties_model/platforms_response.dart'
    as _i2;
import 'package:crypto_tracker_app/data/models/response/coin_response.dart'
    as _i9;
import 'package:crypto_tracker_app/domain/entities/coin.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakePlatformsResponse_0 extends _i1.Fake
    implements _i2.PlatformsResponse {}

class _FakeDescriptionResponse_1 extends _i1.Fake
    implements _i3.DescriptionResponse {}

class _FakeLinksResponse_2 extends _i1.Fake implements _i4.LinksResponse {}

class _FakeImageResponse_3 extends _i1.Fake implements _i5.ImageResponse {}

class _FakeCommunityDataResponse_4 extends _i1.Fake
    implements _i6.CommunityDataResponse {}

class _FakeDeveloperDataResponse_5 extends _i1.Fake
    implements _i7.DeveloperDataResponse {}

class _FakeDateTime_6 extends _i1.Fake implements DateTime {}

class _FakeCoin_7 extends _i1.Fake implements _i8.Coin {}

/// A class which mocks [CoinResponse].
///
/// See the documentation for Mockito's code generation for more information.
class MockCoinResponse extends _i1.Mock implements _i9.CoinResponse {
  MockCoinResponse() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get coinId =>
      (super.noSuchMethod(Invocation.getter(#coinId), returnValue: '')
          as String);
  @override
  String get symbol =>
      (super.noSuchMethod(Invocation.getter(#symbol), returnValue: '')
          as String);
  @override
  String get name =>
      (super.noSuchMethod(Invocation.getter(#name), returnValue: '') as String);
  @override
  _i2.PlatformsResponse get platforms =>
      (super.noSuchMethod(Invocation.getter(#platforms),
          returnValue: _FakePlatformsResponse_0()) as _i2.PlatformsResponse);
  @override
  int get blockTimeInMinutes => (super
          .noSuchMethod(Invocation.getter(#blockTimeInMinutes), returnValue: 0)
      as int);
  @override
  String get algorithm =>
      (super.noSuchMethod(Invocation.getter(#algorithm), returnValue: '')
          as String);
  @override
  List<String> get categories => (super
          .noSuchMethod(Invocation.getter(#categories), returnValue: <String>[])
      as List<String>);
  @override
  _i3.DescriptionResponse get description => (super.noSuchMethod(
      Invocation.getter(#description),
      returnValue: _FakeDescriptionResponse_1()) as _i3.DescriptionResponse);
  @override
  _i4.LinksResponse get links => (super.noSuchMethod(Invocation.getter(#links),
      returnValue: _FakeLinksResponse_2()) as _i4.LinksResponse);
  @override
  _i5.ImageResponse get image => (super.noSuchMethod(Invocation.getter(#image),
      returnValue: _FakeImageResponse_3()) as _i5.ImageResponse);
  @override
  String get genesisDate =>
      (super.noSuchMethod(Invocation.getter(#genesisDate), returnValue: '')
          as String);
  @override
  double get sentimentVotesUpPercentage =>
      (super.noSuchMethod(Invocation.getter(#sentimentVotesUpPercentage),
          returnValue: 0.0) as double);
  @override
  double get sentimentVotesDownPercentage =>
      (super.noSuchMethod(Invocation.getter(#sentimentVotesDownPercentage),
          returnValue: 0.0) as double);
  @override
  int get marketCapRank =>
      (super.noSuchMethod(Invocation.getter(#marketCapRank), returnValue: 0)
          as int);
  @override
  int get coinGeckoRank =>
      (super.noSuchMethod(Invocation.getter(#coinGeckoRank), returnValue: 0)
          as int);
  @override
  double get coinGeckoScore =>
      (super.noSuchMethod(Invocation.getter(#coinGeckoScore), returnValue: 0.0)
          as double);
  @override
  double get developerScore =>
      (super.noSuchMethod(Invocation.getter(#developerScore), returnValue: 0.0)
          as double);
  @override
  double get communityScore =>
      (super.noSuchMethod(Invocation.getter(#communityScore), returnValue: 0.0)
          as double);
  @override
  double get liquidityScore =>
      (super.noSuchMethod(Invocation.getter(#liquidityScore), returnValue: 0.0)
          as double);
  @override
  double get publicInterestScore =>
      (super.noSuchMethod(Invocation.getter(#publicInterestScore),
          returnValue: 0.0) as double);
  @override
  _i6.CommunityDataResponse get communityData =>
      (super.noSuchMethod(Invocation.getter(#communityData),
              returnValue: _FakeCommunityDataResponse_4())
          as _i6.CommunityDataResponse);
  @override
  _i7.DeveloperDataResponse get developerData =>
      (super.noSuchMethod(Invocation.getter(#developerData),
              returnValue: _FakeDeveloperDataResponse_5())
          as _i7.DeveloperDataResponse);
  @override
  DateTime get lastUpdated =>
      (super.noSuchMethod(Invocation.getter(#lastUpdated),
          returnValue: _FakeDateTime_6()) as DateTime);
  @override
  List<Object?> get props =>
      (super.noSuchMethod(Invocation.getter(#props), returnValue: <Object?>[])
          as List<Object?>);
  @override
  _i8.Coin toEntity() => (super.noSuchMethod(Invocation.method(#toEntity, []),
      returnValue: _FakeCoin_7()) as _i8.Coin);
  @override
  List<dynamic> toEntities() =>
      (super.noSuchMethod(Invocation.method(#toEntities, []),
          returnValue: <dynamic>[]) as List<dynamic>);
}
