// Mocks generated by Mockito 5.0.17 from annotations
// in crypto_tracker_app/test/data/datasources/local/crypto_local_data_source_test.dart.
// Do not manually edit this file.

import 'package:crypto_tracker_app/data/datasources/local/object_box_database.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [ObjectBoxDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockObjectBoxDatabase extends _i1.Mock implements _i2.ObjectBoxDatabase {
  MockObjectBoxDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set store(dynamic _store) =>
      super.noSuchMethod(Invocation.setter(#store, _store),
          returnValueForMissingStub: null);
}
