name: crypto_tracker_app
description: Cryptocurrency Tracker Application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.6.5+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  shared_preferences: ^2.0.15
  dio: ^4.0.6
  equatable: ^2.0.3
  google_fonts: ^3.0.1
  hooks_riverpod: ^1.0.4
  cached_network_image: ^3.2.1
  intl: ^0.17.0
  objectbox: ^1.6.0
  objectbox_flutter_libs: any
  path_provider: ^2.0.11
  dartz: ^0.10.1
  internet_connection_checker: ^0.0.1+4
  dcdg: ^4.0.1
  infinite_scroll_pagination: ^3.2.0
  firebase_core: ^1.20.0
  firebase_auth: ^3.6.2
  cloud_firestore: ^3.4.3
  google_sign_in: ^5.4.1
  font_awesome_flutter: ^10.1.0

dev_dependencies:
  flutter_lints: ^2.0.1
  build_runner: ^2.2.0
  objectbox_generator: any
  mockito: ^5.3.0
  http_mock_adapter: ^0.3.3
  flutter_test:
    sdk: flutter

#dependency_overrides:
#  cached_network_image:
#    git:
#      url: https://github.com/XuannThucc/flutter_cached_network_image.git
#      path: cached_network_image
#      ref: ff72f00f142f13d889d7549e013af91cb0b523ab

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700