// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLRbU2JYiAOwbBXbZcLmnGh9_WEU3TaHw',
    appId: '1:767873903886:web:a7285c352260a311cb7b5f',
    messagingSenderId: '767873903886',
    projectId: 'crypto-tracker-app-8755',
    authDomain: 'crypto-tracker-app-8755.firebaseapp.com',
    storageBucket: 'crypto-tracker-app-8755.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRmJZFGwrUHS1eaM0K5u065E63w9p4Tlo',
    appId: '1:767873903886:android:8a879a519734acbecb7b5f',
    messagingSenderId: '767873903886',
    projectId: 'crypto-tracker-app-8755',
    storageBucket: 'crypto-tracker-app-8755.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRgRsOiKeNohGOGIgvBbE6AtNUFbKeIHw',
    appId: '1:767873903886:ios:fa20fcde6aec566ccb7b5f',
    messagingSenderId: '767873903886',
    projectId: 'crypto-tracker-app-8755',
    storageBucket: 'crypto-tracker-app-8755.appspot.com',
    iosClientId: '767873903886-ok657862ff5mk7apis71t0t4hkvtncn2.apps.googleusercontent.com',
    iosBundleId: 'com.crypto.tracker.cryptoTrackerApp',
  );
}
